# Generated by Django 4.2.17 on 2025-01-07 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="pic",
            field=models.ImageField(default="no_image.jpg", upload_to="recipes"),
        ),
    ]
